// all-recycler-cache
plugins {
    id ("com.android.application")
}

android {
    compileSdk = 36
    namespace = "com.all.recyclercache"

    defaultConfig {
        applicationId = "com.all.recyclercache"
        minSdk = 23
        targetSdk = 36

        versionCode = 10630
        versionName = '1.6.30'

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        // Limit languages to following list.
        resConfigs "en", "es"

        buildConfigField "long", "BuildTimeMilli", System.currentTimeMillis() + "L"

        // Save app version in string so resource can be used in layouts
        resValue "string", "versionName", "v" + versionName
    }

    signingConfigs {
        release
    }

    // Load signing config (does not work for command line builds)
    // println("Setting release=${rootDir}/release.properties")
    if (file("${rootDir}/release.properties").exists()) {
        def props = new Properties()
        props.load(new FileInputStream(file("${rootDir}/release.properties")))
        android.signingConfigs.release.storeFile = file(props.keyStore)
        android.signingConfigs.release.storePassword = props.keyStorePassword
        android.signingConfigs.release.keyAlias = props.keyAlias
        android.signingConfigs.release.keyPassword = props.keyAliasPassword
        println("Setting release to " + signingConfigs.release.storeFile.absolutePath )
    }

    buildFeatures.buildConfig = true
    buildFeatures.resValues = true

    buildTypes {
        release {
            // Enables code shrinking, obfuscation, and optimization.
            minifyEnabled = true

            // List of resources removed at end of generated mapping file:
            // grep unused ./app/build/outputs/mapping/demoRelease/resources.txt
            shrinkResources = true

            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig = signingConfigs.release

            ndk {
                // abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
                abiFilters 'armeabi-v7a', 'arm64-v8a'
            }
        }
    }

    gradle.projectsEvaluated {
        tasks.withType(JavaCompile).tap {
            configureEach {
                // Enable verbose lint reporting during build.
                options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
            }
        }
    }
}

dependencies {
    // Add Android support libraries
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation "androidx.annotation:annotation:1.10.0"
    implementation "androidx.recyclerview:recyclerview:1.4.0"
}

// Rename app
androidComponents {
    onVariants(selector().all(), { variant ->
        def ourName = project.parent.name
        def versionStr = variant.outputs[0].versionName.get()
        def newName = "$ourName-${variant.name}-${versionStr}"

        variant.outputs.forEach { output ->
            output.outputFileName.set("${newName}.apk")
        }
        println "out name= ${newName}.apk"
    })
}